project:
  type: website
  preview: 
    watch-inputs: true
    navigate: true
    browser: false
    port: 4200

website: 
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  sidebar: 
    style: docked
    search: true
    collapse-level: 1
    contents: 
      - auto: mathe/
      - auto: deutsch/
      - auto: biologie/
      - auto: geschichte/
      - auto: philosophie/

#bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: de
    toc: true
  #pdf:
  #  documentclass: scrreprt

execute: 
  freeze: auto