project:
  type: book
  preview: 
    watch-inputs: true
    navigate: true
    browser: false
    port: 4200

book:
  title: "Schule"
  author: "Erik Grobecker"
  #date: "3/8/2024"
  #downloads: [pdf, epub]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Biologie"
      chapters: 
        - biologie/ökosysteme.qmd
    - part: "Deutsch"
      chapters: 
        - deutsch/spracherwerbstheorien.qmd
    - part: "Mathe"
      chapters: 
        - mathe/vektor-integrale.qmd
    - part: "Philosophie"
      chapters: 
        - philosophie/kultur-essay.qmd
    - summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: de
  #pdf:
  #  documentclass: scrreprt
