project:
  type: website
  preview: 
    watch-inputs: true
    navigate: true
    browser: false
    port: 4200

book:
  title: "Schule"
  author: "Erik Grobecker"
  #date: "3/8/2024"
  #downloads: [pdf, epub]
  search: true
  repo-url: "https://github.com/Marethyu9999/quarto"
  repo-actions: [issue, edit, source]
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Biologie"
      chapters: 
        - biologie/ökosysteme.qmd
    - part: "Deutsch"
      chapters: 
        - deutsch/spracherwerbstheorien.qmd
    - part: "Mathe"
      chapters: 
        - mathe/vektor-integrale.qmd
    - part: "Philosophie"
      chapters: 
        - philosophie/kultur-essay.qmd
    - part: "Geschichte"
      chapters: 
        - geschichte/juli-krise.qmd
  appendices:
    - tesstrain/tesstrain.qmd

website: 
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  sidebar: 
    style: docked
    search: true
    collapse-level: 1
    contents: 
      - auto: mathe/
      - auto: deutsch/
      - auto: biologie/
      - auto: geschichte/
      - auto: philosophie/

#bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: de
    toc: true
  #pdf:
  #  documentclass: scrreprt

execute: 
  freeze: auto