project:
  type: website
  render:
  - "*.qmd"
  - "!test.qmd"
  - "!sport.qmd"

website:
  title: "Schule"
  navbar:
    left:
      - href: index.qmd
        text: Hauptseite
      # - about.qmd

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true