project:
  type: website

website:
  title: "Schule"
  navbar:
    left:
      - href: index.qmd
        text: Hauptseite
      # - about.qmd

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true