project:
  type: website
  preview: 
    watch-inputs: true
    navigate: true
    browser: false
    port: 4200

website: 
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  navbar: 
    background: primary
    search: true
    left: 
      - text: Home
        file: index.qmd
      - text: "Schule"
        file: schule/index.qmd
      - text: "Software"
        file: software/index.qmd
  sidebar: 
    - title: "Schule"
      style: docked
      search: true
      collapse-level: 1
      contents: 
        - schule/index.qmd
        - auto: schule/mathe/
        - auto: schule/deutsch/
        - auto: schule/biologie/
        - auto: schule/geschichte/
        - auto: schule/philosophie/
    - title: "Software"
      style: docked
      search: true
      collapse-level: 1
      contents: 
        - software/index.qmd
        - auto: software/*


#bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: de
    toc: true
  #pdf:
  #  documentclass: scrreprt

execute: 
  freeze: auto