---
services:
  code-server:
    image: 6d6d96c3ff05
    #build: .
    container_name: vscode-quarto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - DOCKER_MODS=linuxserver/mods:code-server-docker|linuxserver/mods:code-server-extension-arguments
      - VSCODE_EXTENSION_IDS=${EXTENSIONS}  # these here are just my favourite
    volumes:
      - ../../:/config/workspace # for my workspace
    ports:
      - 8443:8443
    restart: unless-stopped