---
title: "Philosophie am 13.03.2024"
lang: de
author: Erik Grobecker
format: html
---

## Handlungs- und Regel-Utilitarismus (von Frankena auf S. 174 M23)

-   Handlungsutilitarismus

    -   Prinzip der Nützlichkeit
    -   die meisten guten Konsequenzen finden
    -   Folgen einer einzelnen Handlung

-   Regel-Utilitarismus

    -   Regeln, ohne Rücksicht auf die möglichen besten Folgen, folgen
    -   Regeln sollten dem größten gemeinen Wohl entsprechend gewählt werden.
        -   also nach dem Prinzip der Nützlichkeit
    -   Regeln sollen überwiegend oft gute Folgen haben.

### Text von John Stuart Mill in dieses Kriterium einordnen (S. 166, M17)

-   Mill findet, dass manche Arten des Glücks *qualitativer* sind als andere, vor allem wenn *höhere Fähigkeiten* gefordert werden.
    -   könnten somit Regeln genutzt werden, um Menschen auf dieses Glück zuzubewegen?
    -   Wenn durch Regelung die *höheren Fähigkeiten* gefördert würden, würden *höhere Fähigkeiten* gefordert werden können.
        -   Somit würde eine *höhere Qualität* für die meisten erreicht werden und **Regeln wären angebracht.**
-   Utilitarismus fordert Unparteilichkeit als wohlwollender Zuschauer
    -   geht sehr in die Richtung des Handlungsutilitarismus
        -   Da Regeln die Unparteilichkeit beeinträchtigen würden