---
title: "Integrale"
lang: de
format:
  html:
    code-fold: true
---

### Was sind Integrale?

**Die Integralrechnung** ist ein **Zweig der Infinitesimalrechnung**, der zusammen mit der **Differentialrechnung** die mathematische **Analysis** bildet. Sie ist aus der Aufgabe entstanden, **Flächeninhalte oder Volumina zu berechnen**, die durch gekrümmte Linien oder Flächen begrenzt sind. 

Unter dem Oberbegriff **Integral** werden das **unbestimmte** und das **bestimmte Integral** einer Funktion zusammengefasst. Hier sind die wichtigsten Aspekte:

1. **Unbestimmtes Integral**: Eine Funktion *F* ist eine **Stammfunktion** der Funktion *f*, wenn ihre Ableitung *F'* genau die ursprüngliche Funktion *f* ist. Das unbestimmte Integral wird verwendet, um Stammfunktionen zu finden.
2. **Bestimmtes Integral**: Das bestimmte Integral einer Funktion *f* ergibt eine **Zahl**. Es gibt den Inhalt der Fläche an, die im Intervall zwischen dem Graphen von *f* und der *x*-Achse liegt. Die Integrationsgrenzen *a* und *b* definieren den Bereich.

### Wie werden Integrale gebildet?

Ein Beispiel eines Integrals ist $\int_{-1}^{1} (2x + 1)dx$, welcher folgendes aussagt:<br>
Der Bereich von dem wir den Flächeninhalt wollen ist **-1 bis 1** und die Formel der Funktion ist $f(x)=2x+1$.

### Hauptsatz der Differenzial- und Integralrechnung

$$
\int_{a}^{b}  f(x)t=F(b)-F(a)
$$

- $F(x)$ ist die Stammfunktion der Funktion $f(x)$.
- $F(x)$ ist somit $f(x)$ hochgeleitet (heißt umgekehrtes Ableiten)

#### Beispiel des Haupsatzes der Integralrechnung

::: {.panel-tabset}

##### Die Formel finden: 
$\int_0^4 x^2 dx$

##### $f(x)$ finden (heißt die Zahlen vor dx lesen): 
$f(x)=x^2$

##### $F(x)$ finden (hochleiten): 
$F(x) = \frac{1}{3} * x^3$

##### $a$ und $b$ einsetzen und ausrechnen: 
$F(4) - F(0) = 21,\overline{3} + 0 = 21,\overline{3}$

   - oder das Ergebnis in einer anderen schreibweise: $f(x) = x^2; [0;4]; F(x)=\frac{1}{3}x^3$
:::