---
title: "Mathe am 13.03.2024"
lang: de
author: Erik Grobecker
format: pdf
toc: true
---

Noten sind nächste Woche\
es gibt anscheinend nächste Woche ein Fußballturnier\
Quarto -\> Tabelle auf S. 185 in drawio mit benötigten Schritten

# windschieffe Schnittpunkte

## S. 187 Nr. 3c)

$g: \vec{x}=\begin{pmatrix}0\\1\\1\end{pmatrix}+t*\begin{pmatrix}1\\0\\1\end{pmatrix}$; $h: \vec{x}=\begin{pmatrix}4\\2\\4\end{pmatrix}+s*\begin{pmatrix}2\\1\\1\end{pmatrix}$

$\begin{pmatrix}1\\0\\1\end{pmatrix} \neq t*\begin{pmatrix}2\\1\\1\end{pmatrix}$

$g=h$\
$\begin{pmatrix}0\\1\\1\end{pmatrix}+t*\begin{pmatrix}1\\0\\1\end{pmatrix}=\begin{pmatrix}4\\2\\4\end{pmatrix}+s*\begin{pmatrix}2\\1\\1\end{pmatrix}$

$I: t=4+2s$\
$II: 1=2+s$\
$III: 1+t=4+s$\

$II: 1=2+s \mid-2$\
$-1=s$

$I: t=4-2=2$

$III: 1+2=4-1$\
$3=3$ ➔ heißt es gibt einen Schnittpunkt

$s$ in Gleichung g einsetzen:\
$\begin{pmatrix} 4 \\ 2 \\ 4 \end{pmatrix}-1\times \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix}=\begin{pmatrix} 4 \\ 2 \\ 4 \end{pmatrix}+\begin{pmatrix} -2 \\ -1 \\ -1 \end{pmatrix}=\begin{pmatrix} 2 \\ 1 \\ 3 \end{pmatrix}$ oder eher (2\|1\|3) (als Punkt)

## HA: Nr. 4 bis morgen (14.03.2024)

# Skalarprodukt

$\neq$ Vektorprodukt

## Beispiel:

$\vec{a}=\begin{pmatrix} 7 \\ 11 \\ 6 \end{pmatrix}\vec{b}=\begin{pmatrix} 0 \\ 1 \\ 2 \end{pmatrix}$\
$\vec{a}\times \vec{b}=7\times 0+11\times 7+6\times 2$\
$=23$ ➔ Produkt ist ein *Skalarprodukt*

## 2. Beispiel:

$\vec{a}=\begin{pmatrix} -1 \\ -4 \\ 7 \end{pmatrix}\vec{b}=\begin{pmatrix} 0 \\ 11 \\ -2 \end{pmatrix}$\
$\vec{a}\times \vec{b}=\left( -1\right) \times 0+\left( -4\right) \times 11+7 \times (-2)$\
$=0-44-14$\
$=(-58)$

## Orthogonale Vektoren

$\vec{a}\times\vec{b}=0$\
➔ $\vec{a}$ ist senkrecht zu $\vec{b}$

### Beispiel:

$\vec{a}=\begin{pmatrix} 2 \\ 2 \end{pmatrix}\vec{b}=\begin{pmatrix} -2 \\ 2 \end{pmatrix}$

Wie überprüft man ob Geraden orthogonal sind?\
man multipliziert die Richtungsvektoren

### S. 190 Nr. 1a)

$g:\vec{x}=\begin{pmatrix} 2 \\ -2 \\ 0 \end{pmatrix}+s\times\begin{pmatrix} -5 \\ 1 \\ 0 \end{pmatrix}$; 
$h:\vec{x}=\begin{pmatrix} 5 \\ -1 \\ 0 \end{pmatrix}+s\times \begin{pmatrix} -2 \\ 2 \\ 0 \end{pmatrix}$\
$\begin{pmatrix} -5 \\ 1 \\ 0 \end{pmatrix}^{x}\begin{pmatrix} -2 \\ 2 \\ 0 \end{pmatrix}=(-5)\times(-2)+1\times2+0\times0$\
$=-10+2$\
$=-8$

