name: Build and Publish Container

on:
  push:
    tags:
      - 'container*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v2
        with:
          context: software/docker/
          push: true
          tags: ghcr.io/marethyu9999/code-server:latest
        env:
          DOCKER_USERNAME: ${{ secrets.GHCR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GHCR_TOKEN }}

