name: Build and Publish Container

on:
  push:
    tags:
      - 'container*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v5
        with:
          context: software/docker
          push: true
          tags: ghcr.io/marethyu9999/vscode-quarto:latest
