name: vscode-quarto build & publish

on:
  push:
    tags:
      - 'container*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v5
        with:
          context: software/docker
          push: true
          tags: ghcr.io/marethyu9999/vscode-quarto:latest